macos_instance:
  image: ghcr.io/cirruslabs/macos-runner:tahoe

task:
  name: Lint

  install_script:
    - brew install golangci-lint

  lint_script:
    - golangci-lint run -v --timeout 4m0s --output.json.path golangci.json

  always:
    report_artifacts:
      path: golangci.json
      format: golangci

task:
  name: Test

  install_script:
    - brew install go

  test_script:
    - go test -v ./...

task:
  name: Build

  install_script:
    - brew install go

  build_script:
    - make build
