task:
  name: Lint

  macos_instance:
    image: ghcr.io/cirruslabs/macos-runner:sonoma

  install_script:
    - brew install golangci-lint

  lint_script:
    - golangci-lint run -v --timeout 4m0s --out-format json > golangci.json

  always:
    report_artifacts:
      path: golangci.json
      format: golangci

task:
  name: Build

  macos_instance:
    image: ghcr.io/cirruslabs/macos-runner:sonoma

  install_script:
    - brew install go

  build_script:
    - make build
