env:
  - CGO_ENABLED=0
  - API_VERSION={{ if index .Env "API_VERSION"  }}{{ .Env.API_VERSION }}{{ else }}x5.0{{ end }}

before:
  hooks:
    # We strongly recommend running tests to catch any regression before release.
    # Even though, this an optional step.
    - go test ./...
    # As part of the release doc files are included as a separate deliverable for
    # consumption by Packer.io. To include a separate docs.zip uncomment the following command.
    # - make ci-release-docs
    # Check plugin compatibility with required version of the Packer SDK
    - make plugin-check
builds:
  -
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath #removes all file system paths from the compiled executable
    ldflags:
      - '-s -w -X {{ .ModulePath }}/version.Version={{.Version}}'
    goos:
      - darwin
    goarch:
      - arm64
      - amd64
    binary: '{{ .ProjectName }}_v{{ .Version }}_{{ .Env.API_VERSION }}_{{ .Os }}_{{ .Arch }}'
snapshot:
  name_template: "{{ if eq .Summary .Tag }}{{ .Version }}{{ else }}{{ incpatch .Version }}-dev{{ end }}"
archives:
- format: zip
  files:
    - none*
  name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Env.API_VERSION }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS'
  algorithm: sha256
release:
  # If you want to manually examine the release before its live, uncomment this line:
  # draft: true
  # As part of the release doc files are included as a separate deliverable for consumption by Packer.io.
  # To include a separate docs.zip uncomment the extra_files config and the docs.zip command hook above.
  # extra_files:
  #   - glob: ./docs.zip

changelog:
  use: github-native
